[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "/.netlify/functions/api" 